### ISSUE TITLE
Where is the credit?

### ISSUE THREAD

**Issue by tanercanbilgin** [theosanct0s/haxball-bot#2]
You should have some respect to the owner of this code.. [@wazarr94](https://github.com/wazarr94/)

**Comment by theosanct0s** [comment]
I would even give credits, but I don't know and I didn't get any code from this user. I took it from other people, putting together and tidying up the code to make it easier to use for lay people who want to create a bot.

**Comment by tanercanbilgin** [comment]
I didn't want you to feel bad, i thought you were one of the disrespectful "codders" in haxball. There's a really big efford in his code and it should be appreciated. 

You can see the original code from [here](https://github.com/Wazarr94/haxball_bot_headless/tree/master/OLD)

**Comment by theosanct0s** [comment]
That's fine and I apologize for passing on that opinion. Really the skeleton of the bot is the same (with some better thought functions) however, actually I took it from third parties that must have originally come from this one and I just modified it making it easier and adding some other functions.
