### ISSUE TITLE
ENGLISH!!!!

### ISSUE THREAD

**Issue by Youssef-Lehmam** [theosanct0s/haxball-bot#3]
You should add the english language to the BOT

**Comment by theosanct0s** [comment]
I put a new version in English. You should look in `var teamIDs` and in `room.sendAnnouncement("Uniforms:` for you to put the uniforms of your country's team, that I can't change for you.

**Comment by theosanct0s** [comment]
Here too, which are the ranks per goal, you should put the name you prefer: `room.sendAnnouncement("「𝐃𝐎𝐍𝐎」" + player.name + ": " + msg + "", null, 0xD81826)`
