### ISSUE TITLE
how to change the current uniforms ?

### ISSUE THREAD

**Issue by Youssef-Lehmam** [theosanct0s/haxball-bot#6]
Uniforms: !atl, !ast, !tot, !ars, !mun, !mci, !ita, !che, !juv, !psg, !gre, !ibi, !bor, !liv, !fra, !rea, !vas, !cori, !cru, !hol, !san, !spfc, !fla, !bra, !bay, !mil, !bot, !esp."

This commands don't work 
any solution ?

**Comment by theosanct0s** [comment]
sorry for the delay and inconvenience, these commands are disabled for now, in the next update of the room they will work again.
